CHROMA_DB_IMPL = "duckdb+parquet"
CHROMA_PERSIST_DIR = "./chroma"
EMBEDDING_MODEL = 'sentence-transformers/all-MiniLM-L12-v2'

DESIGN_DOCUMENTS_DRIVE_FOLDER_ID = '1C8rjAAZfwekllNAUHEewsSPvrivTMiT0'
DESIGN_DOCUMENTS_COLLECTION = 'designdocs'

COLLECTION_NAME = DESIGN_DOCUMENTS_COLLECTION
COLLECTION_DRIVE_FOLDER_ID = DESIGN_DOCUMENTS_DRIVE_FOLDER_ID

COLLECTIONS = ['Docs', "Real Talks"]

GITLAB_COS_SEARCH_PROJECT_ID = 29547683
GILTAB_COS_DOCUMENTATION_PROJECT_ID = 23242714
